Changes for container startup option handling

diff --git a/src/lib/singletons-0.05/instances b/src/lib/singletons-0.05/instances
--- a/src/lib/singletons-0.05/instances
+++ b/src/lib/singletons-0.05/instances
@@ -45,7 +45,7 @@ singletons::instance::select_config() {
         return $?
     elif [ -d .git ]
     then
-        git branch "${name}"
+        git checkout "${name}"
     else
         hg branch "${name}"
     fi
@@ -68,7 +68,7 @@ singletons::instance::names() {
         return $?
     elif [ -d .git ]
     then
-        git branch | awk '{print $NF;}'
+        git branch --list -a | sed -e 's/^[\ \*]*//g' | awk -F/ '{print $NF;}' | grep -v '^master$' | sort -u
     else
         hg branches | awk '{print $1;}'
     fi
@@ -132,6 +132,35 @@ singletons::instance::stop() {
     sudo docker rm "${singleton_name}"
 }
 
+singletons::instance::get_run_options() {
+    local name=${1:?Need instance name}
+    local repo=
+
+    convert_parameters() {
+        for ((i=1; i <= ${#@}; ++i)) {
+            eval echo "\$$i"
+        }
+    }
+
+    logging::info "Building container image ${image_name}"
+
+    if ! singletons::instance::select_config "${name}"
+    then
+        return $?
+    elif ! repo="$(singletons::repo)"
+    then
+        logging::error "Can't access repo folder '${repo}'"
+        return $?
+    elif -f "${repo}/options.txt"
+    then
+        eval convert_parameters "$(
+            cat "${repo}/options.txt" |
+            sed -e 's/#.*$//g' -e '/^[ ]*$/d' |
+            tr '\n' ' '
+        )"
+    fi
+}
+
 singletons::instance::start() {
     local name=${1:?Need instance name}
     local image_name="$(echo "${name}" | tr '[A-Z]' '[a-z]')"
@@ -167,17 +196,33 @@ singletons::instance::start() {
 
     logging::info "Starting container instance ${image_name} as ${singleton_name}"
 
-    case "${image_name}" in
-        *)
-            sudo docker run \
-                -v /home/dkw:/home/dkw \
-                -e TZ="Canada/Atlantic" \
-                --name "${singleton_name}" \
-                --memory=1g \
-                --cpus=0.5 \
-                -d "${image_name}"
-            ;;
-    esac
+    local extra_options=()
+    local _row
+
+    local profile_dir="${HOME}/tmp/profile.${image_name}"
+
+    if [ ! -d "${profile_dir}" ]
+    then
+        mkdir -p "${profile_dir}"
+    fi
+
+    chmod -R 770 "${profile_dir}"
+    chown -R 1000 "${profile_dir}"
+
+    while read _row
+    do
+        extra_options[${#extra_options[@]}]="${_row}"
+    done <<< "$( eval singletons::instance::get_run_options "${name}" )"
+
+    sudo docker run \
+        -v /home/dkw:/home/dkw \
+        -e TZ="Canada/Atlantic" \
+        --name "${singleton_name}" \
+        -v "${profile_dir}:/home/developer" \
+        --memory=1g \
+        --cpus=0.5 \
+        -d "${image_name}" \
+        "${extra_options[@]}"
 }
 
 singletons::instance::attach() {
diff --git a/src/lib/singletons-0.05/subcommands/config-repo b/src/lib/singletons-0.05/subcommands/config-repo
--- a/src/lib/singletons-0.05/subcommands/config-repo
+++ b/src/lib/singletons-0.05/subcommands/config-repo
@@ -135,10 +135,13 @@ do
                 rm -rf "${repo_path}"
             fi
 
-            if is_git "${2}" && ! git clone "${2}" "${repo_path}"
+            if is_git "${2}"
             then
-                logging::error "Cannot clone from GIT repo '${2}'"
-                exit 200
+                if ! git clone "${2}" "${repo_path}"
+                then
+                    logging::error "Cannot clone from GIT repo '${2}'"
+                    exit 200
+                fi
             elif ! hg clone "${2}" "${repo_path}"
             then
                 logging::error "Cannot clone from Mercurial repo '${2}'"
@@ -157,7 +160,7 @@ do
                     logging::error "No such path '${repo_path}'"
                 elif [ -d .git ]
                 then
-                    git branch | awk '{print $NF;}'
+                    git branch --list -a | sed -e 's/^[\ \*]*//g' | awk -F/ '{print $NF;}' | grep -v '^master$' | sort -u
                 else
                     hg branches | awk '{print $1;}'
                 fi
